panoplyio/ep

.travis.yml, rows.go
pretty awesome go race detection :)
found one error. committing it separately so you can see detected race in [first travis log](https://travis-ci.org/panoplyio/ep/builds/292015912).
=> avoid race conditions as part of travis build

dataset.go, dataset_test.go, nulls.go
sometimes dataset can contain recurring columns, i.e. the underlying array of two different i, j columns is identical.
calling dataset[i].swap and dataset[j].swap will result in unsorted array.
therefore, i made dataset unsortable (panics on swap and less), and created an extension that calls swap and less only on unique columns. i.e. only once for each unique underlying array.
@avinoamr not sure if the new api is the best option, will be happy to hear what do you think. 10x :)
=> add sortableDataset to handle recurring columns

dataset.go, ep_test.go, nulls.go, project.go
project should read i-th batch from all runners, without letting some runners to proceed. 
old version using `runOne` recursion function allowed most left runner (at index 0) to proceed. 
bonus: Expand shouldn't panic on mismatch number of rows, but return suitable error
=> project runs and read from all runners without recursion

.travis.yml, distribute.go, distribute_test.go, exchange_test.go
- upgrade to go 1.10
- fix example data race by using log to print err:
```
WARNING: DATA RACE
Read at 0x000000a971b0 by goroutine 85:
fmt.Println()
...
Previous write at 0x000000a971b0 by main goroutine:
testing.runExample.func2()
```
=> fix example data race by using log to print err + upgrade to go 1.10

test_utils.go
It slows down the tests for no apparent reason, and if there's a reason - it makes me wonder how is this deterministic?
@aviaoh this random sleep was introduced in commit 46d80c8117d5631434bfdb588a0772ba1848b937 . This commit only has the comment "Update test_utils.go". The comment in the code is just as confusing. Care to elaborate about why we need it?
Also - is there are reason that this function is exposed if its only used for tests?
=> Remove the random sleep in tests.

.travis.yml, pipeline_test.go
I plan on updating the pipeline code to be flat, instead of recursive - like you did in project. But first, I wanted to have a benchmark to compare against. This is mostly here for discussion about how we do benchmark tests. In this example, I wanted to measure the runtime/allocations per dataset.
=> First experimental benchmark test for pipelines

.travis.yml, exchange.go, pipeline.go
To keep the Pipeline implementation consistent in design to the new Project implementation. Also refactored the Pipeline construction code to remove the repetitive test for passthroughs. Benchmarks were unaffected by this change.
=> Refactor the pipeline to not use recursion

.travis.yml, distribute_test.go, ep_test.go, exchange.go, exchange_test.go, pipeline.go, pipeline_test.go, project.go, project_test.go
1. In case of error in one of the Project runners, drain the Project input.
2. Add listening for cancellation in Project
3. In case of error in one of the project runners, drain others runners outs channel until empty and cancel them. 
4. Adding Mutex to Infinity runner for preventing data race.
5. Adding WaitGroup to Project for preventing data race.
6.Travis scripts run test 100 times
[Asana Task](https://app.asana.com/0/292366464513646/552995392156857)
=> fix project hiding errors

data_example_test.go, data_utils_example_test.go, dataset.go, dataset_sort_test.go, dataset_test.go, distribute.go, distribute_test.go, ep.go, ep_test.go, eptest/cluster.go, eptest/data.go, eptest/eptest.go, exchange.go, exchange_internal_test.go, exchange_test.go, nulls_test.go, pipeline_internal_test.go, pipeline_test.go, project.go, project_test.go, rows_test.go, runner_example_test.go, union_example_test.go
Currently ep exposes some tests utils functions, that shouldn't be used from production code. Therefore, we would like to move public tests utilities to other package.
The convention in go for that case is to expose other package ends with `test` for utilities only (not actual tests, just utilities).
- ep tests should still be located in ep_test (public) ep (private). see pipeline_test vs. pipeline_internal_test
- test **utilities** that are used by ep_test, epsilon, or any other ep user - should be located in eptest package
This PR also contains:
- solve exchange deadlock (see [comment](https://github.com/panoplyio/ep/pull/58/files?diff=unified#diff-e3fccc860d65cb2b1ea65ef992358a08R95))
- modify TestProject_errorWithExchange to actually test exchange within project and pipline
=> separate ep tests to different package + fix exchange deadlock

data.go, data_utils_example_test.go
As requested in #62, this PR removes `Partition` function since it is not used and not needed anywhere. The name `Partition` will be assigned to another function that creates a partition exchange runner (#62)
=> Remove Partition function

plan.go
During the implementation of the reflection package, I found several cases where I can to re-implement the logic from `query/func.go` that checks the arguments of the planned runners. Since the `RunnerArgs` interface is part of the `ep` package, it makes sense to support this filtering in a generic manner to all `ep` users without code repetition.
=> Support the GetWithArgs() and PlanWithArgs() functions

exchange.go, exchange_test.go
When there's no distributer.
This is useful for tests or generic code (like in `ep-join`) where the exchange runners can be used (Scatter, Gather, etc.), yet the whole operation doesn't necessarily distributes the runner via a Distributer.
=> Allow exchange runners to run (short-circuted) locally

dataset.go, dataset_test.go
record/dataset can not be created without concrete types.
this pr allows sending records to the util functions `NewDatasetLike` and `NewDatasetTypes`
=> support record in NewDatasetLike

exchange.go
Currently exchange runners can't run more than once. It's a silly limitation that's easy to solve (with a per-query uid and reinitialization in the init() function - I can explain further...), but in #80 I introduced a change that allowed local exchange runners to run more than once (resulting in a weird panic later). We should really address this, but in the meantime I'm fixing it with the same test that's currently used for distributed queries.
=> Disallow running exchange repeatedly (even locally)

dataset.go
We should support an empty dataset in the API's dataset functions.
For example, the same as we doing in Expand.
=> support empty dataset Width & NewDatasetLike functions

pipeline.go, pipeline_test.go
This PR adds `Args` implementation to `pipeline`. From this point, we will be able to cast pipelines to `RunnerArgs` when needed. Pipelines will use the first runner to determine the result of `Args`. If the first runner in a pipeline will not implement `RunnerArgs` itself, the cast might fail due to `Pipeline` constructor optimizations (not every `Pipeline()` call results in a new instance of `pipeline` struct).
=> Add Args() to pipeline runner

pipeline.go
[Task](https://app.asana.com/0/573768021211412/499296949137123/f)
Since `passthrough` can now include types, we should only filter it when it is a singleton instance that is the same every time.
=> Fix passThrough filtering in pipeline

plan.go
This change is required to support gob encoding of complete AST nodes.
=> Register keys as well as values with gob

dataset.go, dataset_test.go, exchange.go, exchange_internal_test.go, exchange_test.go
This PR adds support for partitioning data based on multiple columns.
It also changes the way data is prepared for partitioning. Instead of slicing every row and keeping everything in memory grouped by encoder (connection), it is now sorts the data, and slices only complete chunks, which are sent to target nodes immediately.
Hashing in `getRowHash` does not have to be unique, it just has to be consistent: same data should end up on the same nodes.
=> Support multiple cols in Partition

distribute.go, distribute_test.go, ep_test.go, pipeline.go, project_test.go
This PR ignore cancel error and doesn't distribute it across the cluster.
cancel error can be thrown when query was canceled on purpose or when a runner is done before its preceding.
=> propagate cancel error, without distribute it

distribute.go, ep_test.go, pipeline.go, pipeline_test.go, project.go, rows_test.go
Pipeline should not propagate cancel error.
in case one of pipeline runners got cancel - cancel other runners and return.
wrapping project/pipeline will treat it as any other termination of runner
=> Pipeline should hide cancel errors

dataset_test.go, distribute.go, eptest/eptest.go, pipeline.go, pipeline_test.go, project.go, runner.go, runner_test.go, union.go
[Task](https://app.asana.com/0/573768021211412/773980942769093)
wrap pipeline `inp` channel with cancel listening, to make sure all consecutive runners will be closed (either if they listen to ctx.done or only to inp).
only pipeline and project are covered at this point.
exchange will be handled in separate PR.
========
**EDIT**: this PR also introduces changes in current approach regarding executors responsibilities.
each place that **both** a) creates channels and b) executes runner should:
1. close out channel at the end (same as today)
2. drain inp channel to allow preceding runner to continue without stuck and be canceled
for that purpose, new function named `ep.Run` was added. `ep.Run` takes care of 1 & 2.
every place that creates channels and executes runner, should use this new …
=>  close pipeline in case of cancel

batch.go
This PR handles a special case where small batches should not be sliced, when they fit into a buffer entirely.
=> Prevent unnecessary slices in Batch

alias.go, pipeline.go, pipeline_test.go, project.go, project_test.go, runner.go, runner_example_test.go
[Task](https://app.asana.com/0/573768021211412/1107587400397456/f)
Since we sometimes need to estimate the size of Runners' output, some runners should be marked as the ones that can estimate their own size. These runners will be called `ApproxSizer`s.
=> Add ApproxSizer interface

runner.go
Tail signature can be simplified to avoid mismatched arguments
=> clean tail signature

alias.go, composition.go, exchange_partition.go
[asana](https://app.asana.com/0/573768021211412/992588584934659)
add AliasSetter interface to allow setting alias within runner without wrapping it with `alias` runner. (following https://github.com/panoplyio/epsilon/pull/304#discussion_r257580448)
=> add AliasSetter interface

data.go, data_builder_test.go, data_example_test.go, dataset.go, dataset_test.go, dummy.go, eptest/data.go, type.go
[Task](https://app.asana.com/0/573768021211412/987829874929256/f)
This PR adds a new `DataBuilder` interface and extends `Type` interface to support it. It also contains a `DataBuilder` implementation for `dataset` type, which uses underlying `Data`'s `DataBuilder` jobjects.
These are some benchmarks I wrote to compare our current `Append` performance vs `DataBuilder`:
```
BenchmarkDataBuilder/integer/DataBuilder-4                 10000            124918 ns/op          809176 B/op         14 allocs/op
BenchmarkDataBuilder/integer/Append-4                       3000            483025 ns/op         4593611 B/op        121 allocs/op
BenchmarkDataBuilder/string/DataBuilder-4                   2000            747980 ns/op         1611994 B/op         14 allocs/op …
```
=> DataBuilder interface

batch.go, dummy.go
[Task](https://app.asana.com/0/573768021211412/987829874929257/f)
Depends on #135 
This PR changes `batch` runner implementation to use a more effective `DataBuilder` instead of regular `Append` calls.
=> Use DataBuilder in Batch runner

data.go, data_builder_test.go, data_example_test.go, dataset.go, dummy.go, ep_internal_test.go, ep_test.go, eptest/data.go, eptest/eptest.go, type.go
[Task](https://app.asana.com/0/573768021211412/1110349877739578/f)
This PR removes deprecated `Append` method from `Data` interface. `DataBuilder` should be used instead.
This PR also removes `DataEmpty` method from `Type` interface since it is not needed anymore after `DataBuilder` introduction.
=> Remove Append and DataEmpty from ep.Data and ep.Type interfaces

distribute_test.go, ep_test.go, exchange_sortgather_test.go, pipeline.go, pipeline_test.go
[asana](https://app.asana.com/0/573768021211412/1111457154294716)
In case another runner that isn't listening to cancellation running an internal pipeline we should make sure that the inner pipeline will drain its input after the inner pipeline cancellation so the flow won't be stuck.
For more details, you can look in the asana task comments.
=> drain pipeline  inputs

pipeline.go, pipeline_test.go
[Task](https://app.asana.com/0/573768021211412/1107574389242163/f)
Pipeline needs to look not only at the latest runner to determine its
size, but to the previous runners as well, until a known size is found.
=> Fix pipeline ApproxSize implementation

dataset.go, dataset_test.go
[Task](https://app.asana.com/0/573768021211412/1114646624434307/f)
This PR fixes data race in `dataset.Expand` method, which was caused by `append`'s modification of dataset's underlying array. Now, we will allocate a new array during `Expand`, and return it, instead of modifying the incoming array.
=> Prevent data race in dataset.Expand

ep_internal_test.go, exchange_internal_test.go, exchange_partition.go, exchange_test.go
[Task](https://app.asana.com/0/573768021211412/1113513046356670/f)
Prior to this change, `ep.Partition` sent every unique row to target nodes one by one, creating a lot of IO/CPU overhead. This PR changes `ep.Partition` implementation to split data into datasets per target node before sending. It means that every batch that arrives to partition will trigger at most N `Encode` calls, where N is the number of nodes.
=> Group data by endpoints during partition

alias.go, compose.go, compose_test.go, ep_test.go, pipeline.go, pipeline_internal_test.go, plan.go, project.go, project_internal_test.go, runner.go, runner_example_test.go
[task](https://app.asana.com/0/573768021211412/1116651220616812)
Compose and composeProject are far more efficient.
This PR uses composable whenever possible seamlessly for every call to `ep.Pipeline` or `ep.Project`
=>  use composable when possible

dataset.go, exchange_scatter.go, rows.go
[Task](https://app.asana.com/0/573768021211412/1121420027311669/f)
This PR replaces a couple of interface calls with more efficient expressions. It also improves columns allocation in `Rows`.
=> Avoid implicit cast and allocs if possible

dataset.go, dataset_test.go, exchange_partition.go
[task](https://app.asana.com/0/573768021211412/1121714234603823)
ColumnStrings is frequently used, so minor optimizations are required here :)
avoid allocations and casting in ColumnStrings
=> avoid allocations and casting in ColumnStrings

dataset.go, project.go, project_test.go
In run time (not in plan time), I changed the implementation of Run() such that we won't use Expand() method each time, but only on the first time of each batch. After the first time, we allocate a Data array of size equals to the width of the data from the first iteration.
**PPROF** results, before and after, can be seen in the PR's [Task](https://app.asana.com/0/573768021211412/1123190355912217)
A possible improvement to the PR is to implement it in **plan time**
=> Reduce the use of Expand in project

eptest/data.go
Part of [asana task](https://app.asana.com/0/573768021211412/1123376548775050)
Copy already changed the newNullIdx in the current data that's why we receive an error in `	require.False(t, data.IsNull(newNullIdx))
`
we should look on another index for this test.
=> fix null idx check in TestData_CopyNTimes_withNulls_

const.go, const_test.go
[task](https://app.asana.com/0/573768021211412/1128472809787652)
this new runner returns const data, calculated at plan time, that duplicates data according to input size.
it's also composable of course
=> create general const runner to handle any type
