panoplyio/ep

.travis.yml
data.go
data_test.go
data_utils_test.go
dataset.go
distribute.go
ep.go
ep_test.go
exchange.go
exchange_test.go
nulls.go
pipeline.go
pipeline_test.go
plan.go
project.go
project_test.go
rows.go
rows_test.go
runner.go
runner_test.go
type.go
union.go
union_test.go

first commit is not interesting. 
@avinoamr please review only [second commit ](https://github.com/panoplyio/ep/pull/3/commits/4358441677637d91cb24ae0e1db0976b753298b6). thanks :)

formatting and linting existing code + force both

---

data.go
data_test.go
dataset.go
nulls.go

add duplicate and expand functions to api

---

data_test.go
data_utils_test.go
ep_test.go
exchange_test.go
grouprun_test.go
pipeline_test.go
project_test.go
rows_test.go
runner_test.go
test_utils.go
union_test.go

encapsulate tests stuff + expose general test_utils to be used by epsilon

---

plan.go

add registry convention comment

---

alias.go
distribute.go
ep.go
pipeline_test.go
rows.go
runner_test.go

example of usage can be seen in branch https://github.com/aviaoh/epsilon/tree/range+as
(or specific [supported syntax](https://github.com/aviaoh/epsilon/blob/range%2Bas/test.sql#L79))
@avinoamr thanks :)

Aliasing + scoping columns

---

exchange.go

Revert "Debug join"

---

data_example_test.go
dataset.go
nulls.go
type.go

extend api with more efficient version of type.Data(int)

---

data_example_test.go
dataset.go
type.go
union.go

Extend api

---

alias.go
type.go

change modifier to be internal interface + add getter

---

dataset.go
dataset_sort.go
dataset_sort_test.go
dataset_test.go
nulls.go
pipeline.go
pipeline_test.go
type.go

- re-implement sort (and remove GetSortable function from dataset interface)
- support wildcard cutting
- minor errors improvements

re-implement sort + support wildcard cutting

---

dataset_sort.go

fixing slow sorting was inserted in #32 🤓

improve sort performance

---

dataset_sort.go
distribute.go
distribute_test.go
ep_test.go
exchange.go
exchange_test.go
rows_test.go
test_utils.go

This pr includes:
- exchange transmit only data/EOF, not real errors
- distribute is in charge of collection all errors from peers

Errors handling

---

pipeline.go
pipeline_test.go
plan.go

create only flat pipelines without nested pipelines or redundant passThrough runners.

Flat pipeline during creation

---

.travis.yml

travis just fixed the issue:
https://github.com/travis-ci/travis-build/pull/1310

update travis build to use latest go 1.10.x

---

distribute_test.go

unstable test.
re-enable it once #44 will be merged

skip distribute test until exchange will be fixed

---

dataset.go
dataset_sort_test.go
nulls.go
pipeline_test.go
project.go
runner.go

Nulls should only be data, not dataset.
There is no such a thing null dataset, and one can use dataset with single null column or dataset without any columns.
bonus: new test for Pick with multiple indices.
@shirHornstein - thanks :)

remove nulls dataset implementation + add test for pick

---

.travis.yml

Rotating the slack token with a new one, This time its encrypted using the `travis` cli tool

Rotate slack token with encrypted version

---

ep_test.go
mapinpout_test.go

Related to: https://github.com/panoplyio/ep/pull/65

Fix the compiled docs that didn't show the expected output

---

pipeline_internal_test.go
project.go
project_internal_test.go
project_test.go

flat added in https://github.com/panoplyio/ep/pull/65 without tests

flat project + add tests

---

data.go
data_example_test.go
dataset.go
dataset_test.go
ep_test.go
eptest/data.go
exchange.go
exchange_internal_test.go
exchange_test.go
nulls.go
project_test.go

- clean ep tests + renaming
- add LessOther function as preparation for distribute sort. LessOther allows to compare two specific elements in two different data objects (unlike Less which is only within same data object)

add LessOther function + clean some tests

---

data.go
data_utils_example_test.go
dataset.go
dataset_test.go
nulls.go

[Asana task](https://app.asana.com/0/573768021211412/666564693065790)
fix a bug in dataset.Append to not affect "other" argument

fix dataset.Append to not affect "other" argument

---

type_test.go

add test for AreEqualTypes, to verify Any is handled correctly

add test for AreEqualTypes

---

.travis.yml

see https://github.com/golang/lint/issues/415

update golint path

---

distribute.go
ep.go
project.go

remove errProjectState and let actual error to be picked

remove errProjectState

---

eptest/eptest.go

is needed for [this pr](https://github.com/panoplyio/ep-store/pull/38)

add BenchWithContext to eptest

---

dataset_sort.go
dataset_sort_test.go

[task](https://app.asana.com/0/573768021211412/958661175721799)

ignore dummies columns in ep.Sort

---

ep_test.go
eptest/eptest.go
eptest/runner.go
pipeline_test.go
project_test.go
runner_test.go

part of [this](https://app.asana.com/0/573768021211412/927432313808528) asana task

move errRunner to eptest

---

alias.go
composition.go
composition_test.go
ep_test.go

[Task 1](https://app.asana.com/0/573768021211412/975404887721589/f), [Task 2](https://app.asana.com/0/573768021211412/975404887721590/f)
This PR introduces a new concept - composition. In general, composition comes to replace as much `ep.Pipeline` and `ep.Project` as possible by combining functions instead of runners.
In addition to new types, this PR implements `composition` type (alternative to pipeline) and `project` type (alternative to project runner).
See new tests that demonstrate how to use composition.

Introduce composition concept

---

ep_test.go
runner_example_test.go

add `scopesRunner` example with data

improve scopesRunner example

---

runner.go

reverting change in #139 and clean ambiguous argument

clean tail signature

---

alias.go
composition.go
composition_test.go

Revert "Modifications in order to support for composable pushing in a better way"

---

alias.go
compose.go
compose_test.go

Reverts panoplyio/ep#145
Or in other words returns https://github.com/panoplyio/ep/pull/141
This change is not backwards compatible, do not merge w/o all dependents!

Modifications in order to support for composable pushing in a better way

---

compose.go
compose_test.go

part of [asana](https://app.asana.com/0/573768021211412/573956241176025)
no need to wrap single composable with composeProject

create project only for multiple composables

---

runner.go

part of [task](https://app.asana.com/0/573768021211412/573956241176025)
make passThrough implement Composable

make passThrough implement Composable

---

project.go
project_test.go

same as https://github.com/panoplyio/ep/pull/149
depend on https://github.com/panoplyio/ep/pull/149

Project drain inp

---

exchange.go

[asana task](https://app.asana.com/0/573768021211412/1113456694480813)
SC should be added to the termination encoders, not into the regular encoders.

don't add SC into gather encoders

---

union.go

[Task](https://app.asana.com/0/573768021211412/1119435387698054/f)
This PR extends `Union` runner to implement `ScopesRunner` and `ApproxSizer`.

Add Scopes() and ApproxSize() to Union

---

alias.go
batch.go
compose.go
dataset_sort.go
dataset_sort_test.go
distribute.go
ep_internal_test.go
ep_test.go
eptest/runner.go
exchange.go
pipeline.go
pipeline_test.go
project.go
rows.go
runner.go
type.go
union.go

[asana task](https://app.asana.com/0/573768021211412/1121774691866202)
in order to compare two runners, we should add Equals function to all runners.

Add equals interface

---

compose.go

[asana](https://app.asana.com/0/573768021211412/1121774691866202)

Fix Equals function in compose

---

data.go
data_example_test.go
dataset.go
dummy.go
ep_internal_test.go
eptest/data.go

Part of [asana task](https://app.asana.com/0/573768021211412/1123376548775050)
This function adds the ability to copy serial values multiple times.

Add Data.CopyNTimes function

---

data.go
data_example_test.go
dataset.go
dummy.go
ep_internal_test.go
eptest/data.go

Part of [asana task](https://app.asana.com/0/573768021211412/1123376548775050)
Same as existing `Copy` but with an array of indexes to be copied.

Add Data.CopyByIndexes function 

---

compose.go
compose_test.go
project_test.go

1.  The Project https://github.com/panoplyio/ep/pull/164 needs to be merged.
2. This PR implementation should be modified a bit. The call to the method **verifySameLength()**, needs to be to the function in _dataset.go_

Inline dataset.Expand logic in ComposeProject
